### PR TITLE
Fix presets

### LINKED ISSUE #253: Base preset bricks kernel installation
Hi,

when you choose the base preset to install a Raspberry PI 2 you'll always get a RSOD (Rainbow Screen Of Death) because it'll not install the module ${kernel_meta_package}.
In line 304 of /scripts/etc/init.d/rcS the variable cdebootstrap_cmdline will be completly overwritten.

Using the server preset and everything will be fine.

Greetings
Saij

### PR DESCRIPTION
**Pull request by diederikdehaas**
This PR re-implements the presets configuration so that a kernel is always installed as well as `cpufrequtils` to fully utilize the CPU.

This fixes #253, #277, #279 and #271.

### CODE REVIEW

File: scripts/etc/init.d/rcS [hunk 1]
```diff
@@ -301,40 +301,43 @@ esac
...
+    base_packages="${kernel_meta_package},cpufrequtils,kmod"
 
-    # add latest kernel if rootfstype requires a module. 
-    # Changed it so it is always installed.
-    # Firmware can't be installed just yet, we'll do so at the end
-    if [ "$kernel_module" = true ] ; then
-        cdebootstrap_cmdline="$cdebootstrap_cmdline,${kernel_meta_package}"
-    fi
+    # minimal
+    minimal_packages="fake-hwclock,ifupdown,net-tools,ntp,openssh-server"
```
Comment (goranche) [inline scripts/etc/init.d/rcS]: I'd add ```${base_packages}``` into the list here, not in the include parameter

Comment (goranche) [inline scripts/etc/init.d/rcS]: although I'm not against it like it is, not to be misunderstood :innocent:

File: scripts/etc/init.d/rcS [hunk 2]
```diff
@@ -301,40 +301,43 @@ esac
...
+        minimal)
+            cdebootstrap_cmdline="--flavour=minimal --include=${base_packages},${minimal_packages}"
             ;;
         *)
-            cdebootstrap_cmdline="$cdebootstrap_cmdline,vim-tiny,iputils-ping,wget,ca-certificates,rsyslog,cron,dialog,locales,less,man-db"
-            preset=server
+            # this should be 'server', but using '*' for backward-compatibility
+            cdebootstrap_cmdline="--flavour=minimal --include=${base_packages},${minimal_packages},${server_packages}"
+            if [ "$preset" != "server" ]; then
+                echo "Unknown preset specified: $preset"
```
Comment (goranche) [inline scripts/etc/init.d/rcS]: maybe add "using server instead" to this echo?

File: scripts/etc/init.d/rcS (hunk 1 above)
Comment (diederikdehaas) [inline scripts/etc/init.d/rcS]: I had it like that at first, but changed it into what it is now. Don't recall right now what the reasoning of it was ...

File: scripts/etc/init.d/rcS [hunk 3]
```diff
@@ -301,40 +301,43 @@ esac
...
+            fi
             ;;
     esac
 
-    # add extra packages
+    dhcp_client_package="isc-dhcp-client"
+    # add dhcp client if using dhcp
+    if [ "$ip_addr" = "dhcp" ]; then
```
Comment (goranche) [inline scripts/etc/init.d/rcS]: should we play it safe and assume dhcp if ```${id_addr}``` is empty or even not set? (ok, not set isn't going to happen, I admit)

File: scripts/etc/init.d/rcS (hunk 1 above)
Comment (goranche) [inline scripts/etc/init.d/rcS]: cool

File: scripts/etc/init.d/rcS (hunk 3 above)
Comment (diederikdehaas) [inline scripts/etc/init.d/rcS]: We had it like this all the time. The only thing I did was re-organize the code a bit (and turned the hardcoded package name into a variable).

Comment (goranche) [inline scripts/etc/init.d/rcS]: I know, but if it's changing, why not improve a bit as well :wink: 

it was just a suggestion

File: scripts/etc/init.d/rcS (hunk 2 above)
Comment (diederikdehaas) [inline scripts/etc/init.d/rcS]: Done (with slightly different words).

Comment (goranche) [inline scripts/etc/init.d/rcS]: :+1:

File: scripts/etc/init.d/rcS (hunk 3 above)
Comment (diederikdehaas) [inline scripts/etc/init.d/rcS]: A bit late, but you're actually right :stuck_out_tongue_closed_eyes:
